import type { StaticImageData } from "next/image";
import quiknest_thumb from "@/public/work/quiknest/thumbnail.webp";
import masala_thumb from "@/public/work/masala/thumbnail.webp";
import zaCleaning from "@/lib/clients/za-cleaning";
import dayToday from "@/lib/clients/day-today";

export interface PortfolioItem {
  id: string;
  title: string;
  /** Short client name shown large on the hero */
  clientName: string;
  description: string;
  thumbnail: string | StaticImageData;
  /** Hero background image — falls back to first image or thumbnail */
  heroImage?: string | StaticImageData;
  images: string[];
  date: string;
  category: string;
  challenge?: string;
  solution?: string;
  outcome?: string;
  /** Background colour class for the thumbnail card (e.g. "bg-black") — used when thumbnail is a logo */
  cardBg?: string;
}

export const portfolioItems: PortfolioItem[] = [
  dayToday,
  zaCleaning,
  {
    id: "itspadel",
    title: "Building a Digital Presence for a Padel Academy",
    heroImage: "/portfolio-client-thumbnail/itspadel.png",
    clientName: "It's Padel",
    description: "A comprehensive brand, web, and social media overhaul for a fast-growing padel academy — from zero digital presence to a fully recognisable identity across every touchpoint.",
    thumbnail: "/clients/itspadel-logo.svg",
    cardBg: "bg-black",
    images: [],
    date: "2024-09-01",
    category: "Branding",
    challenge: "It's Padel had no defined visual identity, no dedicated website, and a social media presence that lacked consistency or strategy. Without a cohesive digital presence, the academy was struggling to attract new players and communicate the energy and professionalism of their facilities. Every platform looked different, and there was no clear narrative to draw people in.",
    solution: "RestоRefine partnered with It's Padel across every major discipline — branding, web development, social media, graphic design, and video production. We built a bold, confident visual identity from the ground up: a strong geometric logomark, a vibrant colour system anchored in electric blues and clean whites, and a typographic language that communicates both sport and lifestyle. The website was designed and developed to showcase the academy, its coaching programmes, and booking flow. For social, we created a full content strategy and produced original photography and video content — including on-site shoots and edited reels — giving the team a library of assets to post with authority.",
    outcome: "It's Padel launched with a brand that immediately commanded attention in the padel community. The new website became their primary conversion tool, and their social channels grew rapidly following the launch of consistent, high-quality content. New player enquiries increased significantly, and the academy's reputation as the go-to padel destination in their area was firmly established.",
  },
  {
    id: "yewtreeinn",
    title: "Yew Tree Inn",
    clientName: "Yew Tree Inn",
    description: "Refined print and menu design for a classic British country inn with a warm, welcoming identity.",
    thumbnail: "/clients/yew-tree-inn-logo.svg",
    images: [],
    date: "2025-07-01",
    category: "Menus",
  },
  {
    id: "saladclub",
    title: "Salad Club",
    clientName: "Salad Club",
    description: "A full brand identity exploration for a health-first salad and grain bowl concept.",
    thumbnail: "/work/saladclub/saladclub-logo-prototype-01.webp",
    heroImage: "/clients/saladclub-bg.png",
    images: [],
    date: "2025-12-12",
    category: "Branding",
    challenge: "Salad Club wanted a brand that didn't fall into the tired 'healthy food' visual clichés — they aimed to position themselves as premium, design-conscious, and unapologetically bold.",
    solution: "We explored multiple logo concepts before landing on a confident wordmark system with a deep teal base, clean geometric forms, and a typographic lockup that reads beautifully at any scale.",
    outcome: "The final identity gave Salad Club a strong foundation to build their franchise expansion on, with a visual language that stands out sharply in the health food market.",
  },
  {
    id: "quiknest",
    title: "Quiknest Logo Design",
    clientName: "Quiknest",
    description: "A bold, modern identity for a fast-growing delivery platform. We crafted a logomark and full brand system that communicates speed, trust, and digital-first thinking.",
    thumbnail: quiknest_thumb,
    heroImage: "/clients/quiknest-bg.png",
    images: [
      "/work/quiknest/docs/Artboard 1@2x-100.webp?height=900&width=1600",
      "/work/quiknest/docs/Artboard 2@2x-100.webp?height=900&width=1600",
      "/work/quiknest/docs/Artboard 3@2x-100.webp?height=900&width=1600",
      "/work/quiknest/docs/Artboard 4@2x-100.webp?height=900&width=1600",
      "/work/quiknest/docs/Artboard 5@2x-100.webp?height=900&width=1600",
      "/work/quiknest/docs/Artboard 6@2x-100.webp?height=900&width=1600",
      "/work/quiknest/docs/Artboard 7@2x-100.webp?height=900&width=1600",
      "/work/quiknest/docs/Artboard 8@2x-100.webp?height=900&width=1600",
      "/work/quiknest/docs/Artboard 9@2x-100.webp?height=900&width=1600",
      "/work/quiknest/docs/Artboard 10@2x-100.webp?height=900&width=1600",
    ],
    date: "2024-01-28",
    category: "Branding",
    challenge: "Quiknest needed a brand identity that felt premium yet approachable — something that would stand out in a crowded delivery market while communicating reliability and speed to both consumers and business partners.",
    solution:
      "We developed a confident wordmark paired with a dynamic logomark that nods to movement and connectivity. The colour palette — deep navy and electric accents — was chosen to signal both trust and energy. Every element was crafted for versatility across app icons, packaging, and print.",
    outcome: "The new identity gave Quiknest the visual authority to pitch to investors and launch publicly with confidence. The brand system has since scaled across their app, website, and marketing campaigns seamlessly.",
  },
  {
    id: "masala-moves-by-luna-shree",
    title: "Masala Moves By Luna Shree",
    heroImage: "/portfolio-client-thumbnail/masala-moves.png",
    clientName: "Masala Moves",
    description: "A vibrant brand identity for a Bollywood dance studio that captures the joy, energy, and cultural richness of South Asian dance.",
    thumbnail: masala_thumb,
    images: [
      "/work/masala/docs/Artboard 0@2x-100.webp?height=900&width=1600",
      "/work/masala/docs/Artboard 1@2x-100.webp?height=900&width=1600",
      "/work/masala/docs/Artboard 2@2x-100.webp?height=900&width=1600",
      "/work/masala/docs/Artboard 3@2x-100.webp?height=900&width=1600",
      "/work/masala/docs/Artboard 4@2x-100.webp?height=900&width=1600",
      "/work/masala/docs/Artboard 5@2x-100.webp?height=900&width=1600",
      "/work/masala/docs/Artboard 6@2x-100.webp?height=900&width=1600",
      "/work/masala/docs/Artboard 7@2x-100.webp?height=900&width=1600",
      "/work/masala/docs/Artboard 8@2x-100.webp?height=900&width=1600",
      "/work/masala/docs/Artboard 9@2x-100.webp?height=900&width=1600",
    ],
    date: "2024-01-15",
    category: "Branding",
    challenge: "Luna Shree's Bollywood dance studio had outgrown its original look. She needed a brand that would honour the cultural heritage of her craft while feeling modern enough to attract a new generation of dancers.",
    solution:
      "We created a warm, expressive identity drawing from the rich palettes of South Asian textiles and performance arts. The custom logotype uses fluid letterforms that echo movement and rhythm, while the supporting graphic language references traditional motifs reimagined in a contemporary way.",
    outcome: "The rebrand helped Masala Moves triple their social following within months and launch a successful class booking platform. Luna now uses the brand across merchandise, studio signage, and digital campaigns.",
  },
  {
    id: "big-bites",
    title: "Big Bites",
    clientName: "Big Bites",
    description: "Punchy, appetite-driven menu design for a bold fast-food brand.",
    thumbnail: "/work/bigbites/Artboard 2@4x.webp",
    heroImage: "/clients/big-bites-bg.png",
    images: ["/work/bigbites/Artboard 2@4x.webp", "/work/bigbites/Artboard 1@4x.webp"],
    date: "2024-01-15",
    category: "Menus",
    challenge: "Big Bites needed menus that matched their bold, no-nonsense personality — easy to read, visually exciting, and built to sell.",
    solution: "We designed high-energy menu layouts using strong typography, vivid food photography, and a clear hierarchy that guides customers quickly to their best sellers.",
    outcome: "Staff reported faster customer decision-making at the counter, and the brand's visual identity became instantly recognisable across their locations.",
  },
  {
    id: "everest-inn",
    title: "Everest Inn",
    clientName: "Everest Inn",
    description: "Premium menu design for a celebrated Nepalese restaurant with deep roots and a modern dining vision.",
    thumbnail: "/work/everestinn/everestinn_menudesign-01.webp",
    heroImage: "/clients/everest-inn-bg.png",
    images: ["/work/everestinn/everestinn_menudesign-01.webp", "/work/everestinn/everestinn_menudesign-02.webp"],
    date: "2025-08-05",
    category: "Menus",
    challenge: "Everest Inn wanted menus that reflected the sophistication of their food and service — moving away from generic designs towards something that truly represented their Nepalese heritage.",
    solution: "We crafted an elegant menu using rich earth tones, refined typography, and subtle cultural motifs that evoke the warmth and prestige of the Himalayan highlands.",
    outcome: "The new menus elevated the dining experience, receiving praise from both regulars and first-time guests. The design has since become a core part of the restaurant's brand story.",
  },
  {
    id: "firangi",
    title: "Firangi",
    clientName: "Firangi",
    description: "Bold seasonal menu designs for one of the UK's most talked-about contemporary Indian restaurants.",
    thumbnail: "/work/firangi/firangi_xmasmenu-02.webp",
    heroImage: "/clients/firangi-bg.png",
    images: ["/work/firangi/firangi_xmasmenu-02.webp", "/work/firangi/firangi_xmasmenu-01.webp", "/work/firangi/firangi_drinksmenu-02.webp", "/work/firangi/firangi_drinksmenu-01.webp"],
    date: "2025-10-21",
    category: "Menus",
    challenge: "Firangi needed seasonal menus that felt as exciting as their food — contemporary, confident, and a cut above the typical restaurant print.",
    solution: "We designed a suite of seasonal menus with bespoke illustration-inspired graphic elements, premium paper stock recommendations, and a layout system that works across both food and drinks.",
    outcome: "The seasonal menus became a talking point in their own right, shared widely on social media by diners who appreciated the craft.",
  },
  {
    id: "gurhkaexpress",
    title: "Gurkha Express",
    clientName: "Gurkha Express",
    description: "A clean, well-structured bifold menu design for a beloved Nepalese takeaway and restaurant.",
    thumbnail: "/work/ghurkaexpress/gurkhaexpress_bifold_update5-01.webp",
    heroImage: "/clients/gurhkaexpress-bg.png",
    images: ["/work/ghurkaexpress/gurkhaexpress_bifold_update5-01.webp", "/work/ghurkaexpress/gurkhaexpress_bifold_update5-02.webp"],
    date: "2025-11-19",
    category: "Menus",
    challenge: "Gurkha Express had an extensive menu that was difficult to navigate — customers were overwhelmed and staff spent too long explaining options.",
    solution: "We reorganised the information architecture and designed a clean bifold layout with clear sections, strong typographic hierarchy, and branded colour accents that make ordering effortless.",
    outcome: "Customer feedback on the new menu was immediately positive, and the owners reported a noticeable increase in add-on orders thanks to better dish visibility.",
  },
  {
    id: "himalayandineinn",
    title: "Himalayan Dine Inn",
    clientName: "Himalayan Dine Inn",
    description: "Warm, refined menu design for a family-run Nepalese dining institution.",
    thumbnail: "/work/himalayandineinn/himalayandinein-01.webp",
    heroImage: "/clients/himalayandineinn-bg.png",
    images: ["/work/himalayandineinn/himalayandinein-01.webp", "/work/himalayandineinn/himalayandinein-02.webp"],
    date: "2024-12-23",
    category: "Menus",
    challenge: "Himalayan Dine Inn wanted to honour their heritage while presenting their menu in a way that felt polished and contemporary for a growing UK customer base.",
    solution: "We developed a menu design using warm amber tones, clean serif typography, and a layout that balances cultural pride with modern readability.",
    outcome: "The menus gave the restaurant a renewed sense of identity that resonated deeply with both their existing loyal customers and new visitors.",
  },
  {
    id: "indianbynature",
    title: "Indian By Nature",
    clientName: "Indian By Nature",
    description: "A nature-inspired brand identity and menu suite for an organic Indian dining experience.",
    thumbnail: "/work/indianbynature/ibnmenudesign_printwbleed_update11_ibn1.webp",
    heroImage: "/clients/indianbynature-bg.png",
    images: ["/work/indianbynature/ibnmenudesign_printwbleed_update11_ibn1.webp", "/work/indianbynature/ibnmenudesign_printwbleed_update11_ibn2.webp"],
    date: "2025-09-27",
    category: "Menus",
    challenge: "Indian By Nature positioned themselves around organic, ethically sourced ingredients but their existing menu didn't communicate this ethos at all.",
    solution: "We crafted a nature-forward design language — muted botanical greens, hand-drawn texture elements, and refined typography — to build a unified identity across print and digital touchpoints.",
    outcome: "The redesign helped them attract a health-conscious demographic that had previously overlooked the restaurant, while deepening loyalty among existing guests.",
  },
  {
    id: "mannis",
    title: "Mannis",
    clientName: "Mannis",
    description: "A complete visual identity system for a premium hospitality brand — from logomark to brand guidelines.",
    thumbnail: "/work/mannis/mannis_visualidentity-01.webp",
    heroImage: "/clients/mannis-bg.png",
    images: [
      "/work/mannis/mannis_visualidentity-01.webp",
      "/work/mannis/mannis_visualidentity-02.webp",
      "/work/mannis/mannis_visualidentity-03.webp",
      "/work/mannis/mannis_visualidentity-04.webp",
      "/work/mannis/mannis_visualidentity-05.webp",
      "/work/mannis/mannis_visualidentity-06.webp",
      "/work/mannis/mannis_visualidentity-07.webp",
      "/work/mannis/mannis_visualidentity-08.webp",
    ],
    date: "2025-03-11",
    category: "Branding",
    challenge: "Mannis was launching a new premium hospitality concept and needed a brand identity built from the ground up — one that could scale across restaurant, events, and retail.",
    solution: "We developed a comprehensive visual identity: a refined logomark, a sophisticated neutral-toned colour palette, bespoke typeface pairings, and a full brand guideline document covering every usage scenario.",
    outcome: "Mannis launched with a brand that immediately commanded attention, cited by industry press as one of the most refined new restaurant identities of the year.",
  },
  {
    id: "momohub",
    title: "Momo Hub",
    clientName: "Momo Hub",
    description: "Sleek business card and stationery design for a modern Nepalese street food brand.",
    thumbnail: "/work/momohub/momohub_businesscard_u3-01.jpg",
    heroImage: "/clients/momohub-bg.png",
    images: ["/work/momohub/momohub_businesscard_u3-01.jpg", "/work/momohub/momohub_businesscard_u3-02.jpg"],
    date: "2025-04-21",
    category: "Media",
    challenge: "Momo Hub needed professional stationery that matched the quality of their food and gave them credibility when approaching new venues and wholesale partners.",
    solution: "We designed a premium business card suite using spot UV finishes, clean layout, and a minimal aesthetic that lets the brand's confidence do the talking.",
    outcome: "The new stationery helped Momo Hub secure several new wholesale partnerships within weeks of their launch.",
  },
  {
    id: "ourhq",
    title: "Our HQ",
    clientName: "Our HQ",
    description: "Content creation and social media assets for a co-working space with a strong community identity.",
    thumbnail: "/work/ourhq/ourhq-post1.webp",
    heroImage: "/clients/ourhq-bg.png",
    images: ["/work/ourhq/ourhq-post1.webp", "/work/ourhq/ourhq-post2.webp"],
    date: "2025-12-22",
    category: "Media",
    challenge: "Our HQ had a compelling vision for their space but struggled to communicate it visually on social media — their existing content lacked consistency and polish.",
    solution: "We developed a content strategy and produced a suite of branded social assets, templates, and photography guidelines to give their team the tools to post with confidence.",
    outcome: "Our HQ saw a significant uplift in organic engagement, with several posts reaching new audiences beyond their existing community.",
  },
  {
    id: "pulp",
    title: "Pulp",
    clientName: "Pulp",
    description: "A fresh, contemporary menu design for a vibrant juice bar and café concept.",
    thumbnail: "/work/pulp/pulpmenudesign-02.webp",
    heroImage: "/clients/pulp-bg.png",
    images: ["/work/pulp/pulpmenudesign-02.webp"],
    date: "2025-10-11",
    category: "Menus",
    challenge: "Pulp needed a menu design that felt as fresh and energetic as their product range — a design that would work as well on screen as it did in print.",
    solution: "We created a clean, modern layout with generous white space, a playful colour palette anchored by vibrant greens and citrus tones, and bold product photography placement.",
    outcome: "The redesigned menu became a key piece of brand collateral, used across both their physical location and digital ordering platform.",
  },
  {
    id: "spudkingz",
    title: "Spud Kingz",
    clientName: "Spud Kingz",
    description: "Bold, appetite-driven menu and brand design for a loaded potato concept that punches well above its weight.",
    thumbnail: "/clients/spud-kingz-logo.svg",
    heroImage: "/clients/spudkingz-bg.png",
    images: [],
    date: "2025-06-01",
    category: "Menus",
  },
];
